version: "3"

services:
  scale_server_tasks:
    build: .
    # volumes:
    #   - /Users/logangunn/Github/server-tasks/source:/source_data
    #   - /Users/logangunn/Github/server-tasks/destination:/destination_data
